### ISSUE TITLE
Example of possible issue

### ISSUE THREAD

**Issue by anuzzolese** [whow-project/ontologies#1]
In the ontology network the prefix "core:" should be renamed "ispra-top:".

**Comment by giorgialodi** [comment]
I strongly support this rename because it creates some misunderstanding in the use in WHOW for instance. Shall we do it immediately? :)

**Comment by eliogiulianelli** [comment]
For me yes! 

I propose the following further changes:
- renaming core.owl in **top.owl** and all the relative URI from /ontology/core/ to **/ontology/top/** 
- in the ontology network the prefix "places:" should be renamed "**ispra-loc**:"
- renaming places.owl in **location.owl** and all the relative URI from /ontology/places/ to **/ontology/location/**

**Comment by giorgialodi** [comment]
This has been implemented.
