### ISSUE TITLE
Typo in water monitoring ontology diagram image

### ISSUE THREAD

**Issue by angelogulina** [whow-project/ontologies#12]
The diagram [here](https://github.com/whow-project/ontologies/blob/main/whow-ontology-network/images/water-monitoring-ontology-diagram.jpg) has a typo in `WaterRadioctivityObservation` (should be `WaterRadioactivityObservation`)

<img width="455" alt="Screenshot 2022-06-27 at 16 34 52" src="https://user-images.githubusercontent.com/4223655/175966726-4fdc1c76-24f6-4093-ba24-88bb7f4eafce.png">

**Comment by giorgialodi** [comment]
thanks @angelogulina! @dersuchendee in the new diagram I am editing, this error has been fixed. As soon as we publish the new diagram, we close this issue!

**Comment by dersuchendee** [comment]
New diagram released. Closing the issue. Thanks!

**Comment by dersuchendee** [comment]
New diagram released. Closing the issue. Thanks!
