### ISSUE TITLE
places:istat

### ISSUE THREAD

**Issue by eliogiulianelli** [whow-project/ontologies#4]
In ontology network insert domain and range for property places:**istat**

**Comment by giorgialodi** [comment]
What's istat? IstatCode?

**Comment by eliogiulianelli** [comment]
Yes, for example (in test):
<https://dati.isprambiente.it/ld/places/municipality/082075> <https://dati.isprambiente.it/ontology/places/istat> "082075" .

**Comment by giorgialodi** [comment]
ok so I would call it istatCode then (or istatIdentifier). In anycase, I would suggest you to take a look at OntoPiA where every spatial object may have an identifier (class). In this way you may specify all the identifiers you want for that spatial object. This is quite common according to different (national) databases.

**Comment by eliogiulianelli** [comment]
Yes, we could change it as istatCode (or istatIdentifier). I took a look at OntoPia and Identifier (class). I therefore propose the following changes in the ISPRA ontology:

In "core": 
1) delete the following part from core:**_UniqueIdentifier_**: 
<<rdfs:subClassOf>>
    <<owl:Restriction>>
        <owl:onProperty rdf:resource="https://dati.isprambiente.it/ontology/core/isIssuedBy"/>
        <owl:someValuesFrom rdf:resource="https://dati.isprambiente.it/ontology/core/Organisation"/>
    </owl:Restriction>
</rdfs:subClassOf> 
2) add _identifierType_ in core:**_UniqueIdentifier_**;
3) put _identifierType_ as key field (together _isIssuedBy_ and _identifier_) of core:**_UniqueIdentifier_**.

In "places":
1) If we introduce places:**_SpatialObject_** coherently with GeoSPARQL and OntoPiA, we could coherently align core: **_UniqueIdentifier_** with clv:**_Identifier_**

**Comment by giorgialodi** [comment]
With the latest version of the place ontology the domain and range of that property are correctly valorized.
