### ISSUE TITLE
places:Feature

### ISSUE THREAD

**Issue by eliogiulianelli** [whow-project/ontologies#5]
In ontology network introduce places:**Feature** (in the _alignments_ make it _equivalentClass_ of geo:**Feature**) disjoint from places:**Geometry** and make places:**AdministrativeUnit** a subclass of places:**Feature**, remove in the alignments that places:**AdministrativeUnit** is a subclass of geo:**Feature** and remove that places:**AdministrativeUnit** is disjoint from places:**Geometry**

**Comment by eliogiulianelli** [comment]
1) To make alignments more consistent with OntoPiA perhaps, instead of defining places:**Feature** and places:**Geometry** as _equivalentClassOf_ the homonymous classes of GeoSPARQL (and also of the relative classes of GeoNames, etc.), perhaps they could be defined - as for OntoPiA - as _subClassOf_ of the homonymous classes in GeoSPARQL (and other classes).

2) Also, could we define in OntoPiA clv:**hasGeometry** _subPropertyOf_ geo:**hasGeometry** (as it is clv:**hasGeometry** _subPropertyOf_ locn:**geometry**)?
And therefore consistently with OntoPiA (considering that places:**hasGeometry** is a _equivalentPropertyOf_ clv:**hasGeometry**) we could change:
- from places:**hasGeometry** _equivalentPropertyOf_ geo:**hasGeometry** to places:**hasGeometry** _subPropertyOf_ geo:**hasGeometry**;
- from places:**Geometry** _equivalentClassOf_ geo:**Geometry** to places:**Geometry** _subClassOf_ geo:**Geometry**?

**Comment by giorgialodi** [comment]
fixed with the latest commit [568bc5a](https://github.com/whow-project/semantic-assets/commit/568bc5a7e10dfbdc4329f7b5808ab1abdb9b9d6e)
