### ISSUE TITLE
places:Point, ....

### ISSUE THREAD

**Issue by eliogiulianelli** [whow-project/ontologies#9]
In ontology network possibly introduce the classes places:**Point**, places:**Polygon**, places:**MultiPolygon**, ... (see link  https://inspire-eu-rdf.github.io/inspire-rdf-guidelines/#ref_cr_types_table_mapping_iso19107  for the list of classes or here: https://crossforest.eu/def/spatial-grid/index-en.html) as subclasses of places:**Geometry** and make them _equivalentClass_ (in the _alignments_) to the analogous classes of the Simple Feature ontology (sf < http://www.opengis.net/ont/sf#>, for example sf:**Point**, sf:**Polygon**, sf: **MultiPolygon**, ..., which are all subclasses of geo:**Geometry**)

**Comment by giorgialodi** [comment]
In OntoPiA there is a class named GeometryType that has as individuals some of these. Try to see there too https://w3id.org/italia/onto/CLV

**Comment by eliogiulianelli** [comment]
I took a look at the class GeometryType: the individuals present might be fine: perhaps we should add more. If though  the requirement in "Guidelines for the RDF encoding of spatial data" is mandatory, we could think of introducing subclasses of geo: **_Geometry_**.

See for example as implemented here:
https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/sf_geometries.ttl
https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/alignments/dcmi-alignments.ttl
https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/alignments/geonames-alignments.ttl
https://github.com/opengeospatial/ogc-geosparql/blob/master/1.1/alignments/locn-alignments.ttl

**Comment by giorgialodi** [comment]
It is implemented through GeometryType and hasGeometryType
